import { test, expect } from '@playwright/test'
import path from 'node:path'

test('jornada de campo: endereco, rota, visita, evidencia e OCR', async ({ page }) => {
  test.setTimeout(180_000)
  await page.goto('/')
  await page.getByRole('button', { name: 'Entrar' }).click()
  await page.getByRole('navigation').getByRole('button', { name: /Ocorrências/ }).click()
  await page.getByRole('button', { name: /Nova ocorrência/ }).click()
  const form = page.getByRole('dialog', { name: 'Formulário de ocorrência' })
  await form.getByLabel('Descrição').fill('Visita de campo sintética E2E')
  await form.getByLabel('Endereço').fill('Rua Sintética 1')
  await form.getByRole('button', { name: 'Buscar endereço' }).click()
  await expect(form.locator('.field-visit').first()).toBeVisible()
  await form.locator('.field-visit').first().click()
  await expect(form.getByLabel('Latitude')).not.toHaveValue('')
  const latitude = await form.getByLabel('Latitude').inputValue()
  const longitude = await form.getByLabel('Longitude').inputValue()
  const createdResponse = page.waitForResponse(r => r.url().includes('/api/v1/occurrences') && r.request().method() === 'POST')
  await form.getByRole('button', { name: 'Salvar' }).click()
  const protocol = (await createdResponse).json().then((value: { protocol: string }) => value.protocol)
  const createdProtocol = await protocol
  await page.getByRole('navigation').getByRole('button', { name: /Croqui \/ Rotas/ }).click()
  await page.getByLabel('Buscar ponto da rota').fill(createdProtocol)
  await page.locator('#route-points .check-row').filter({ hasText: createdProtocol }).locator('input').check()
  const routeName = `Rota E2E Sprint 3 ${Date.now()}`
  await page.getByLabel('Nome do plano').fill(routeName)
  await page.getByLabel('Latitude de partida').fill('-15.58')
  await page.getByLabel('Longitude de partida').fill('-56.09')
  await page.getByRole('button', { name: 'Gerar e salvar rota' }).click()
  await expect(page.getByText('Rota salva com sucesso.')).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: /Modo Campo/ }).click()
  await page.getByLabel('Selecionar rota de campo').selectOption({ label: `${routeName} · planned` })
  await page.getByRole('button', { name: 'Iniciar rota' }).click()
  await expect(page.getByText('Rota iniciada.')).toBeVisible()
  await page.context().grantPermissions(['geolocation'])
  await page.context().setGeolocation({ latitude: Number(latitude), longitude: Number(longitude), accuracy: 15 })
  await page.getByRole('button', { name: 'Obter localização' }).click()
  await expect(page.getByLabel('Latitude do check-in')).not.toHaveValue('')
  await page.getByRole('button', { name: 'Registrar check-in agora' }).click()
  await expect(page.getByText('Check-in registrado.')).toBeVisible()
  await page.getByLabel('Latitude de chegada').fill(latitude)
  await page.getByLabel('Longitude de chegada').fill(longitude)
  await page.getByRole('button', { name: 'Confirmar chegada' }).click()
  await page.getByRole('button', { name: 'Iniciar visita' }).click()
  await page.getByLabel('Descrição').fill('Revisita de inspeção sintética')
  await page.getByRole('button', { name: 'Registrar pendência' }).click()
  await page.getByRole('button', { name: 'Resolver pendência' }).click()
  await expect(page.getByText('Pendência resolvida.')).toBeVisible()
  await page.getByLabel('Fotografar ou selecionar arquivo').setInputFiles(path.resolve('../api/fixtures/relatorio_visita_sintetico.png'))
  await expect(page.getByRole('img', { name: 'Prévia da evidência' })).toBeVisible()
  await page.getByRole('button', { name: 'Confirmar envio' }).click()
  await expect(page.getByText('Evidência enviada e OCR solicitado.')).toBeVisible()
  await page.getByRole('button', { name: /Revisar OCR/ }).click()
  await expect(page.getByRole('heading', { name: 'Extração e revisão' })).toBeVisible()
  await expect(page.getByText('Aguardando revisão').first()).toBeVisible({ timeout: 90_000 })
  await page.getByRole('button', { name: 'Aprovar campos' }).click()
  await expect(page.getByText('Revisão aprovada.')).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: /Modo Campo/ }).click()
  await page.getByLabel('Selecionar rota de campo').selectOption({ label: `${routeName} · active` })
  await page.getByRole('button', { name: 'Concluir visita' }).click()
  await page.getByRole('button', { name: 'Encerrar rota' }).click()
  await expect(page.getByText('Rota encerrada.')).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: /Dashboard/ }).click()
  await expect(page.getByText('Operação de campo')).toBeVisible()
})




